services:
  - type: web
    name: propertyscout-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_VERSION
        value: 24.14.1
      - key: FRONTEND_URL
        value: https://propertyscout-frontend.onrender.com

  - type: web
    name: propertyscout-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 24.14.1
      - key: VITE_API_URL
        value: https://propertyscout-backend.onrender.com/api
